name: Sparse Checkout Test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/workflows/
          sparse-checkout-cone-mode: false
      - run: ls -R .github/
